      SUBROUTINE FZOL(ZOL,PHIM,PHIG,PSIM,PSIG)
C FZOL:    SUBROUTINE TO ESTIMATE THE STABILITY FUNCTIONS
CMNT       USING THE MOST UP TO DATE FLUX-PROFILE RELATIONSHIPS
CMNT
      IF (ZOL .GE. 0.0) GO TO 2
CMNT             UNSTABLE
      X=(1.0-16.0*ZOL)**0.25
      PHIM=1.0/X
      PHIG=PHIM**2
      PSIG=2.0*ALOG(0.5+0.5*X**2)
      PSIM=0.5*PSIG+2.0*ALOG(0.5*(1.0+X))-2.0*ATAN(X)+1.571
      RETURN
CMNT
CMNT     STABLE
2     PHIG=1.0+7.0*ZOL
      PHIM=1.0+7.0*ZOL
      PSIG=-7.0*ZOL
      PSIM=-7.0*ZOL
      RETURN
      END          
