      SUBROUTINE LONGWAVE(SST,TAIR,EA,C,RL1,RL2,RLW,RLWC)
CMNT  COMPUTE CLEAR SKY LONGWAVE, RLW, AFTER (CLARKE ET AL,
CMNT  1974) AND CLOUD CORRECTED LONGWAVE, RLWC.
CMNT  INPUT SST (DEG C), TAIR (DEG C), VAPOR PRESSURE (MB),
CMNT  AND CLOUD COVER (DECIMAL, 0 TO 1.0).  EMISSIVITY
CMNT  IS ASSUMED TO BE 0.98; SIGMA=STEFAN-BOLTZMANN CONST.
CMNT
CMNT  R.WELLER, 6/18/87
CMNT
      EPS=0.98
      SIGMA=5.67E-08
      TKEL=273.16
      SSTK=SST+273.16
      TAIRK=TAIR+TKEL
      TS4=SSTK**4.
      TS3=SSTK**3.
      DT=SSTK-TAIRK
      EASQR=SQRT(EA)
      RL1=(EPS*SIGMA*TS4*(0.39-(0.05*EASQR)))
      RL2=4.*EPS*SIGMA*TS3*DT
      RLW=RL1+RL2
CMNT  COMPUTE CLOUD CORRECTION FACTOR (CLARKE ET AL 1974)
CMNT  B=0.62 HARDWIRED FOR 27 DEG NORTH
      B=0.62
      CSQ=C*C
      FC=1-(B*CSQ)
      RLWC=RLW*FC
      RETURN
      END
